### ISSUE TITLE
typo in the main github screen

### ISSUE THREAD

**Issue by aha999** [biqqles/p2oggle#2]
A small device name typo, In the [requirements section](https://github.com/biqqles/p2oggle) and on the XDA [article ](https://forum.xda-developers.com/lenovo-p2/themes/p2oggle-t3965418)you said: 

> I wrote it for the `P2a47` (global variant)

But you probably meant `P2a42`...

PS. Thanks for this project/app and your development on this.

**Comment by biqqles** [comment]
Thanks for pointing this out, you're quite correct.
