### ISSUE TITLE
Sound record function for toggle possible ?

### ISSUE THREAD

**Issue by aha999** [biqqles/p2oggle#4]
Is it possible that the Toggle would enable the start/end of the audio recording with the stock or custom audio recording apps?

if it is, it would be nice to have that option.

Maybe you could implement it to work with specific app, if functionality for all recording apps is not possible.

One opensource recording app that is available on f-droid is:
https://gitlab.com/axet/android-audio-recorder

**Comment by biqqles** [comment]
Addressed [here](https://forum.xda-developers.com/showpost.php?p=81404465&postcount=78). Again, sorry for the late response.
